// examples/react-app/src/App.tsx
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { ReputexWidget } from "reputex-react-widget";

// defineCustomElements();

function App() {
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <ReputexWidget
        visibility
        userAddress="0x570999eEa85adF6957f68125eF77967c208A1095"
        apiAccessKey="019c383a-9ad6-4b68-8226-44d01cd0ff20"
        apiSecretKey="b2bb63b277b5485e927b0d5538f6bd52871522f8162fa71bfd18de54d83e620e"
        mode
      ></ReputexWidget>
    </>
  );
}

export default App;

// examples/vue-app/src/App.vue
<script setup lang="ts"></script>

<template>
  <div>
    <reputex-widget
      visibility
      userAddress="0x570999eEa85adF6957f68125eF77967c208A1095"
      apiAccessKey="019c383a-9ad6-4b68-8226-44d01cd0ff20"
      apiSecretKey="b2bb63b277b5485e927b0d5538f6bd52871522f8162fa71bfd18de54d83e620e"
      mode
    ></reputex-widget>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
